services:
  gdg_linz_backend:
    image: mateocallec/gdg-linz-backend:latest
    container_name: gdg_linz_backend
    restart: unless-stopped
    depends_on:
      - gdg_linz_backend_db
    ports:
      - "7100:80"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=gdg_linz_backend_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ./container-data/storage:/storage
    volumes:
      - ./container-data/storage:/storage
    networks:
      - gdg_linz_backend_net

  gdg_linz_backend_db:
    image: mysql:8.0
    container_name: gdg_linz_backend_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./db/exercises.sql:/docker-entrypoint-initdb.d/exercises.sql
      - ./container-data/mysql:/var/lib/mysql
    networks:
      - gdg_linz_backend_net

volumes:
  mysql_data:

networks:
  gdg_linz_backend_net:
    driver: bridge
