# Use the official PHP image with Apache
FROM php:8.2-apache

# Enable Apache rewrite module
RUN a2enmod rewrite

RUN apt-get update && apt-get install -y libonig-dev libzip-dev unzip \
    && docker-php-ext-install pdo pdo_mysql

# Copy Apache virtual host configuration
COPY apache.conf /etc/apache2/sites-available/000-default.conf

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Add storage mounting point
RUN mkdir -p /storage

# Set permissions
RUN chmod -R 755 /var/www/html
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN chown -R www-data:www-data /storage
RUN chmod -R 777 /storage

# Expose HTTP port
EXPOSE 80

# Use custom entrypoint
ENTRYPOINT ["entrypoint.sh"]
